reviews:
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "develop"
    ignore_usernames:
      - "dependabot[bot]"
      - "github-actions[bot]"

  request_changes_workflow: true
