[package]
name = "md-hinagata-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "md_hinagata_wasm"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
md-hinagata-core = { path = "../md-hinagata-core" }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.121"
